---
output: html_document
---

```{r setup-06, include=FALSE}
library(formattable)
library(dplyr)
library(data.table)
library(ggplot2)
library(stringr)


path = "~/web-of-life-tutorial/data/"
file_name_mod = "modularity_2022-06-24"
file_name_nest = "nestedness_2022-06-21"
file_name_conn = "connectance"

connectance_df <- read.csv(file = paste0(path, file_name_conn,".csv"))
colnames(connectance_df)[1] <- "id"
connectance_df <- mutate(connectance_df, 
                         network_type =  str_sub(connectance_df$network_name, start = 1L, end = 4L)) 

nestedness_df <- read.csv(file = paste0(path, file_name_nest,".csv"))
colnames(nestedness_df)[1] <- "id"
nestedness_df <- mutate(nestedness_df, 
                        network_type =  str_sub(nestedness_df$network_name, start = 1L, end = 4L)) 

modularity_df <- read.csv(file = paste0(path, file_name_mod,".csv"))
colnames(modularity_df)[1] <- "id"
modularity_df <- mutate(modularity_df, 
                        network_type =  str_sub(modularity_df$network_name, start = 1L, end = 4L)) 

```

# Indices of ecological networks in Web of Life 

```{r, eval =FALSE} 
nestedness_df %>% formattable()
```

```{r, eval =FALSE} 
connectance_df %>% formattable()
```

```{r, eval =FALSE} 
modularity_df %>% formattable()
```

## Connectance
```{r} 
ggplot(connectance_df, aes(x=connectance, color=network_type, fill=network_type)) +
  geom_density(alpha = 0.2) + xlim(0, 1)  # alpha is the fill transparency
```

## Nestedness 
```{r} 
ggplot(nestedness_df, aes(x=nestedness_bascompte, color=network_type, fill=network_type)) +
  geom_density(alpha = 0.2) + xlim(0, 1) 
```

```{r} 
ggplot(nestedness_df, aes(x=nestedness_weighted, color=network_type, fill=network_type)) +
  geom_density(alpha = 0.2) + xlim(0, 1) 
```

```{r} 
ggplot(nestedness_df, aes(x=nestedness_temperature, color=network_type, fill=network_type)) +
  geom_density(alpha = 0.2) 
```

## Modularity 
```{r} 
ggplot(modularity_df, aes(x=modularity_fast_greedy, color=network_type, fill=network_type)) +
  geom_density(alpha = 0.2) + xlim(0, 1)  # alpha is the fill transparency
```


```{r} 
ggplot(modularity_df, aes(x=modularity_edge_betweenness, color=network_type, fill=network_type)) +
  geom_density(alpha = 0.2) + xlim(0, 1)  
```


```{r} 
ggplot(modularity_df, aes(x=modularity_leading_eigen, color=network_type, fill=network_type)) +
  geom_density(alpha = 0.2) + xlim(0, 1)  
```

